name: CI
on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:
  schedule:
    - cron: '0 0 * * 1'
jobs:
  build:
    name: "build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Pull docker images
        run: 'parallel docker pull -- xenit/alfresco-repository-skeleton:6.0 alfresco/alfresco-content-repository-community:6.0.7-ga tomcat:7-jre8 hello-world alpine:edge'
      - name: Check
        run: ./gradlew check -PintegrationTestScope=0
      - name: Upload reports
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: reports-build
          path: build/reports
      - name: Upload analysis to sonarcloud
        if: "${{ env.SONAR_TOKEN != '' }}"
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ github.token }}
        run: ./gradlew sonarqube -Dsonar.projectKey=xenit-eu_alfresco-docker-gradle-plugin -Dsonar.organization=xenit-eu -Dsonar.host.url=https://sonarcloud.io -PintegrationTestScope=0
      - name: Publish
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        env:
          GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PLUGINS_PUBLISH_KEY }}
          GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PLUGINS_PUBLISH_SECRET }}
        run: ./gradlew publishPlugins -Pgradle.publish.key=$GRADLE_PUBLISH_KEY -Pgradle.publish.secret=$GRADLE_PUBLISH_SECRET
  integration-test:
    name: "integration-test (slice=${{ matrix.slice }})"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        slice:
          - 0
          - 1
          - 2
          - 3
          - 4
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Pull docker images
        run: 'parallel docker pull -- alfresco/alfresco-content-repository-community:6.0.7-ga tomcat:7-jre8 hello-world alpine:edge'
      - name: Check
        run: ./gradlew check -PintegrationTestSlice.index=${{ matrix.slice }} -PintegrationTestSlice.total=5 -PintegrationTestScope=2
      - name: Upload reports
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: reports-integration-test-${{ matrix.slice }}
          path: build/reports
